version: "3.8"
services:
  cctv-web:
    build: .
    volumes:
      - .:/usr/bin/cctv
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - DATABASE_URL=postgres://postgres@cctv-postgres:5432/postgres
      - SECRET_KEY=$SECRET_KEY
      - ENV=production
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - VIDEO_BUCKET_NAME=$VIDEO_BUCKET_NAME
      - SENDGRID_S3_VIDEO_URL_TEMPLATE_ID=$SENDGRID_S3_VIDEO_URL_TEMPLATE_ID
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
  cctv-celery-workers:
    build: .
    volumes:
      - .:/usr/bin/cctv
    environment:
      - ENV=production
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - VIDEO_BUCKET_NAME=$VIDEO_BUCKET_NAME
      - SENDGRID_S3_VIDEO_URL_TEMPLATE_ID=$SENDGRID_S3_VIDEO_URL_TEMPLATE_ID
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
    entrypoint: ["celery", "-A", "tasks.celery", "worker", "--uid=$UID", "--loglevel=INFO", "--concurrency=10", "-n", "worker1@%h"]
  cctv-celery-workers-video-queue:
    build: .
    volumes:
      - .:/usr/bin/cctv
    environment:
      - ENV=production
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - VIDEO_BUCKET_NAME=$VIDEO_BUCKET_NAME
      - SENDGRID_S3_VIDEO_URL_TEMPLATE_ID=$SENDGRID_S3_VIDEO_URL_TEMPLATE_ID
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
    entrypoint: ["celery", "-A", "tasks.celery", "worker", "--uid=$UID", "--loglevel=INFO", "--concurrency=10", "-n", "worker2@%h", "-Q", "video_queue"]
  cctv-celery-workers-s3-queue:
    build: .
    volumes:
      - .:/usr/bin/cctv
    environment:
      - ENV=production
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - CELERY_BROKER_URL=$CELERY_BROKER_URL
      - VIDEO_BUCKET_NAME=$VIDEO_BUCKET_NAME
      - SENDGRID_S3_VIDEO_URL_TEMPLATE_ID=$SENDGRID_S3_VIDEO_URL_TEMPLATE_ID
      - SENDGRID_API_KEY=$SENDGRID_API_KEY
    entrypoint: ["celery", "-A", "tasks.celery", "worker", "--uid=$UID", "--loglevel=INFO", "--concurrency=10", "-n", "worker3@%h", "-Q", "s3_queue"]
  cctv-postgres:
    image: postgres
    volumes:
      - /home/prithaj/.local/volumes/cctv-postgres-data:/var/lib/postgresql/data
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust 
  cctv-redis:
    image: redis
    restart: always