"""empty message

Revision ID: 689443286ffe
Revises: 57b8660d2f7e
Create Date: 2021-01-19 08:59:18.435054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689443286ffe'
down_revision = '57b8660d2f7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_processing_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_queue', 'fetching_hls_url', 'writing_hls_stream_to_file', 'uploading_file_to_s3', 'emailing_video_to_user', 'done', name='status'), nullable=True),
    sa.Column('video_start_time', sa.DateTime(), nullable=True),
    sa.Column('video_end_time', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_processing_tasks')
    # ### end Alembic commands ###
